#!/usr/bin/env node
/**
 * One authority, one area record.
 *
 * ethnic-projections.json is written by a dozen scripts in sequence, each
 * keyed on whatever code its own input uses. Barnsley reaches the model as
 * E08000016 from the Census 2021 base and as E08000038 from the Home Office
 * local route file and the model's region groupings; Sheffield reaches it as
 * E08000019 and E08000039. Nothing reconciled the two, so both authorities were
 * filed twice, and the enrichment scripts split their writes across the pair:
 * the record under the Census code carried projections_detail, religion,
 * nativity and the stochastic bands, the record under the other code carried
 * smoothedProjections and asylumEthnicImpact, and neither was complete.
 *
 * Worse than incomplete, they disagreed. The duplicate records held projections
 * from two different model runs. Barnsley's 2041 White British share read 85.7%
 * under E08000016 and 77.6% under E08000038. Both were published: /places
 * listed 320 rows for 318 authorities, and every national aggregate that walked
 * the area map counted 801,000 people twice.
 *
 * This step runs after the model and before anything reads the file. For every
 * alias code in src/data/lookups/area-code-aliases.json it either folds the
 * record into the canonical code, when the canonical record is absent, or drops
 * it, when the canonical record is present. It reports what it dropped and
 * which fields went with it, because a dedupe that quietly discards half an
 * authority's data is the same defect one level down.
 *
 * Fields are never merged across the pair. The duplicate records are outputs of
 * different model runs, and a record assembled from both would describe neither:
 * grafting the alias record's smoothedProjections onto the canonical record
 * would publish a smoothing of a superseded projection beside the current one.
 * Anything the canonical record now lacks is regenerated by re-running the
 * script that produces it, which this fix makes alias-aware so it writes to the
 * canonical code.
 *
 *   node scripts/model/canonicalise_area_codes.mjs           # fix and report
 *   node scripts/model/canonicalise_area_codes.mjs --check   # report only, exit 1 if a duplicate is live
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import path from "node:path";

import { AREA_CODE_ALIASES, canonicalAreaCode } from "../lib/area-codes.mjs";

const LIVE_DIR = path.resolve("src/data/live");
const checkOnly = process.argv.includes("--check");

/** An ONS area code: one country letter, one type digit, seven digits. */
const AREA_CODE = /^[ENSWK]\d{8}$/;

/**
 * A code-keyed map is any object whose keys are area codes. Finding them by
 * shape rather than by name catches scenario-summaries.json's scenarioRanges
 * alongside every file's areas map, and will catch the next one without this
 * script having to be told about it.
 */
function codeKeyedMaps(value, keyPath, found) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return found;

  const keys = Object.keys(value);
  const codeKeys = keys.filter((k) => AREA_CODE.test(k));
  if (codeKeys.length > 0 && codeKeys.length === keys.length) {
    found.push({ keyPath, map: value });
    return found;
  }

  for (const [k, v] of Object.entries(value)) {
    codeKeyedMaps(v, keyPath ? `${keyPath}.${k}` : k, found);
  }
  return found;
}

const report = { dropped: [], folded: [], filesChanged: [] };

for (const file of readdirSync(LIVE_DIR).filter((f) => f.endsWith(".json")).sort()) {
  const filePath = path.join(LIVE_DIR, file);
  let data;
  try {
    data = JSON.parse(readFileSync(filePath, "utf8"));
  } catch {
    continue;
  }

  let changed = false;

  for (const { keyPath, map } of codeKeyedMaps(data, "", [])) {
    for (const alias of Object.keys(AREA_CODE_ALIASES)) {
      if (!(alias in map)) continue;
      const canonical = canonicalAreaCode(alias);
      const aliasRecord = map[alias];
      const name = aliasRecord?.areaName ?? canonical;

      if (canonical in map) {
        const kept = map[canonical];
        const lostFields = Object.keys(aliasRecord ?? {}).filter((k) => !(k in (kept ?? {})));
        report.dropped.push({
          file,
          keyPath,
          alias,
          canonical,
          name,
          lostFields,
          keptWbi2041: kept?.projections?.["2041"]?.white_british ?? null,
          droppedWbi2041: aliasRecord?.projections?.["2041"]?.white_british ?? null
        });
        if (!checkOnly) {
          delete map[alias];
          changed = true;
        }
      } else {
        report.folded.push({ file, keyPath, alias, canonical, name });
        if (!checkOnly) {
          map[canonical] = aliasRecord;
          delete map[alias];
          changed = true;
        }
      }
    }
  }

  if (changed) {
    writeFileSync(filePath, JSON.stringify(data, null, 2), "utf8");
    report.filesChanged.push(file);
  }
}

const total = report.dropped.length + report.folded.length;

console.log(`Area code canonicalisation across ${readdirSync(LIVE_DIR).filter((f) => f.endsWith(".json")).length} live data files\n`);

console.log(`  duplicate records under an alias code: ${report.dropped.length}`);
for (const d of report.dropped) {
  const proj =
    d.keptWbi2041 != null && d.droppedWbi2041 != null
      ? `, 2041 WBI kept ${d.keptWbi2041}% vs dropped ${d.droppedWbi2041}%`
      : "";
  console.log(`      ${d.file} ${d.keyPath}: ${d.name} ${d.alias} dropped for ${d.canonical}${proj}`);
  if (d.lostFields.length > 0) {
    console.log(`          fields only on the dropped record: ${d.lostFields.join(", ")}`);
  }
}

console.log(`\n  records filed under an alias code with no canonical record: ${report.folded.length}`);
for (const f of report.folded) {
  console.log(`      ${f.file} ${f.keyPath}: ${f.name} ${f.alias} refiled as ${f.canonical}`);
}

if (checkOnly) {
  console.log(`\n  --check: ${total === 0 ? "no alias codes live" : `${total} alias codes live, run without --check to fix`}`);
} else {
  console.log(`\n  files rewritten: ${report.filesChanged.length}`);
  for (const f of report.filesChanged) console.log(`      ${f}`);
}

process.exit(checkOnly && total > 0 ? 1 : 0);
